export const wilayasPricing = [
  {
    name: "zone1",
    wilayas: ["alger"],
    price: 500,
  },
  {
    name: "zone2",
    wilayas: ["Blida", "Boumerdes", "Tipaza"],
    price: 600,
  },
  {
    name: "zone3",
    wilayas: ["Tizi_ouzou", "Medea", "Bouira", "Djelfa"],
    price: 700,
  },
  {
    name: "zone4",
    wilayas: [
      "Oum_el_bougui",
      "Batna",
      "Bejaia",
      "Tebessa",
      "Jijel",
      "Setif",
      "Skikda",
      "Annaba",
      "Guelma",
      "Constantine",
      "Msila",
      "Bba",
      "El_taref",
      "Souk ahras",
      "Mila",
      "Khenchla",
      "Chlef",
      "Tlemcen",
      "Tiaret",
      "Saida",
      "Sidi_bel_abbes",
      "Mostaganem",
      "Mascara",
      "Tissemsilt",
      "Ain_timouchent",
      "Relizane",
      "Oran",
      "Ain_defla",
      "Ouargla",
      "Laghouat",
    ],
    price: 800,
  },
  {
    name: "zone5",
    wilayas: [
      "Adrar",
      "Bechar",
      "Biskra",
      "El_Bayedh",
      "El_ouad",
      "Illizi",
      "Naama",
      "Tindouf",
      "Ghardaia",
      "Tamenrasset",
    ],
    price: 950,
  },
];
